apiVersion: v1
kind: Secret
metadata:
  name: postgres{{ .Values.environment.suffix }}-secret
  labels:
    app: postgres{{ .Values.environment.suffix }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  POSTGRES_DB: postgres
