apiVersion: v1
kind: Service
metadata:
  name: postgres{{ .Values.environment.suffix }}
  labels:
    app: postgres{{ .Values.environment.suffix }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: postgres
  selector:
    app: postgres{{ .Values.environment.suffix }}
